name: class_22_docker_action
on: [push]

jobs:
  class_22_docker_action:
    name: Push Docker image to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ DOCKERHUB_USERNAME }}
          password: ${{ DOCKER_PASSWORD }}
          
      - name: Docker Metadata action
        id: metadata
        uses: docker/metadata-action@v5.7.0
        with:
          images: cmuriukin/class_22_repo

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          label: ${{ steps.metadata.outputs.labels }} 
          
