# name: Class 20 Docker Build publish Workflow
# on: push
# jobs:
#   Class-20-Docker-Build-publish-Workflow:
#     name: Class 20 Docker Build publish
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4.1.7

#       - name: Log into Docker hub
#         uses: docker/login-action@v3.3.0
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Extract Metadata(Tags and Labels)
#         id: metadata
#         uses: docker/metadata-action@v5.5.1
#         with:
#           images: cmuriukin/class-20

#       - name: Build and Publish Docker Image
#         uses: docker/build-push-action@v6.6.1
#         with:
#           context: .
#           push: true
#           tags: |
#             cmuriukin/class-20:latest
#             ${{ steps.metadata.outputs.tags }}
#             ${{ github.GITHUB_RUN_NUMBER }}
#           labels: ${{ steps.metadata.outputs.labels }}
          #
name: Docker Build and Publish

on:
  push:
    branches: [ class20 ]  # Adjust this to your main branch name
  pull_request:
    branches: [ class20 ]

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: cmuriukin/class-20
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,format=long

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
          
    
