name: Publish Docker Image
on: [push]
jobs:
  push_image_to_registry:
    name: Push Docker Image to registry
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Log into Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (labels, tags)
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: cmuriukin/class19

      - name: Build and publish the docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    
    
