name: Hello World
on: push
jobs:
  print-hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Wiat for 30 seconds
        run: sleep 30
      - name: Print Hello World
        run: echo "Hello World"
