name: My multi steps  workflow
on: push


jobs:
  multi_stages_ci:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4.2.2
       - name: Build
         run: |
           sleep 10
           echo "sleep 10"
       - name: Tag
         run: |
           echo "Docker tag...."
       - name: docker push
         run: |
           echo "Docker Push"
          
        
    
